with-expecter: true
recursive: true

filename: "{{- lower .InterfaceName}}.mock.go"
outpkg: "mock{{.PackageName}}"
dir: "mocks/{{.PackageName}}"

packages:
  github.com/sazonovItas/go-moco-proxy/pkg/connpool:
    config:
      dir: "pkg/connpool/mock/{{.PackageName}}"
    interfaces:
      Dialer:

  net:
    interfaces:
      Conn:
