// Code generated by "stringer -type=Level -linecomment"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelDebug-0]
	_ = x[LevelInfo-1]
	_ = x[LevelWarn-2]
	_ = x[LevelError-3]
}

const _Level_name = "debug-levelinfo-levelwarn-levelerror-level"

var _Level_index = [...]uint8{0, 11, 21, 31, 42}

func (i Level) String() string {
	if i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
