name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install dependencies and generate code
        run: |
          go get -v -t -d ./...
          go generate ./...

      - name: Test with cli tools
        run: |
          go test -v ./... -race
     
