name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ 1.21, 1.22, 1.23 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies and generate code
        run: |
          go get -v -t -d ./...
          go generate ./...

      - name: Test with cli tools
        run: |
          go test -v ./... -race
     
