name: release 

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: go-releaser
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        name: Checkout code
        with:
          fetch-depth: 0

      - name: Set up Go1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
