name: release 

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: go-releaser
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go-version: [ 1.21, 1.22, 1.23 ]

    steps:
      - name: Set up Go1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v4

      - name: Install dependencies and generate code
        run: |
          go get -v -t -d ./...
          go install golang.org/x/tools/cmd/stringer@latest
          go generate ./...

      - name: Test with cli tools
        run: |
          go test -v ./... -race
     
